### ISSUE TITLE
Change upstream language server

### ISSUE THREAD

**Issue by bollwyvl** [jupyter-lsp/json-lsp#7]
Thanks for getting this going!

It looks like the current language server `vscode-json-languageserver-bin@1.0.1`, probably originally chosen in `jupyterlab-lsp` because it was a single `.js` file, might never get updated again, and isn't very well documented. It's somewhat hard to know what behavior quirks are due to already-fixed-upstream bugs or (sheepishly) my use of it in environments with `jupyterlab-lsp`.

The [_upstream_'s upstream](https://github.com/microsoft/vscode/tree/main/extensions/json-language-features/server) _has_ been getting updates (currently `vscode-json-languageserver@1.3.4`, but does _not_ have a single-file distribution.

Perhaps [`ncc`](https://www.npmjs.com/package/@vercel/ncc) could be used at build time of _this_ package to generate an equivalent single-file distribution, such that no `node_modules` would be included, only a single `json-language-server-bin`.

Will do some investigating...

Semi-related: it's probably now appropriate to start dreaming how we'd get high-value language servers like this into jupyterlite... https://github.com/jupyterlite/jupyterlite/issues/390#issuecomment-943549483

**Comment by martinRenou** [comment]
Thanks for bringing this up!

Yeah we should totally update this. We might also want to move this repo outside of my personal account. Maybe under https://github.com/jupyter-lsp, I am opening another issue for that.

**Comment by bollwyvl** [comment]
Of note: initial `ncc` says:

```yaml
[D 2021-10-14 12:24:54.238 ServerApp] 101 GET /lsp/ws/json-language-server (127.0.0.1) 0.95ms
[D 2021-10-14 12:24:54.246 ServerApp] <LspStdIoWriter(parent=<LanguageServerSession(language_server=json-language-server, argv=['json-lsp'])>)> initialized
[D 2021-10-14 12:24:54.247 ServerApp] <LspStdIoReader(parent=<LanguageServerSession(language_server=json-language-server, argv=['json-lsp'])>)> initialized
[D 2021-10-14 12:24:54.247 ServerApp] [json-language-server] Opened a handler
[D 2021-10-14 12:24:54.247 ServerApp] Opening websocket /lsp/ws/json-language-server
[D 2021-10-14 12:24:54.248 ServerApp] [json-language-server] Handling a message
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module './services/jsonCompletion'
Require stack:
- 👻/json-lsp/json_lsp/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at 👻/json-lsp/json_lsp/dist/index.js:4515:28
    at 👻/json-lsp/json_lsp/dist/index.js:4505:17
    at Object.8994 (👻/json-lsp/json_lsp/dist/index.js:4511:3)
    at __nccwpck_require__ (👻/json-lsp/json_lsp/dist/index.js:14119:43)
    at Object.7226 (👻/json-lsp/json_lsp/dist/index.js:3810:39)
    at __nccwpck_require__ (👻/json-lsp/json_lsp/dist/index.js:14119:43) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '👻/json-lsp/json_lsp/dist/index.js' ]
}

```

:ghost:
